name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: 1.89.0
          components: clippy, rustfmt, llvm-tools-preview

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --locked --verbose

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy (deny warnings)
        run: cargo clippy --all --all-features -- -D warnings

      - name: Test
        run: cargo test --all --all-features --quiet

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
        continue-on-error: true

      - name: Coverage (lcov)
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info
        continue-on-error: true

      - name: Coverage (html)
        run: cargo llvm-cov --workspace --html --output-path coverage/html
        continue-on-error: true

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            lcov.info
            coverage/html

      - name: Upload coverage to Codecov (non-blocking)
        if: always()
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false


